package oksvg

import "testing"

func TestSetTarget(t *testing.T) {
	type Box struct {
		X, Y, W, H float64
	}

	// SetTarget has no return value, what we actually test is that the
	// Transform matrix generated by SetTarget maps from ViewBox to Target
	tests := []struct {
		ViewBox Box // icon ViewBox
		Target  Box // projection target for SetTarget
	}{
		// projections requiring only translation
		{ViewBox: Box{0, 0, 24, 24}, Target: Box{0, 0, 24, 24}},
		{ViewBox: Box{0, -24, 24, 24}, Target: Box{0, 0, 24, 24}},
		{ViewBox: Box{-24, 0, 24, 24}, Target: Box{0, 0, 24, 24}},
		{ViewBox: Box{-24, -24, 24, 24}, Target: Box{0, 0, 24, 24}},
		{ViewBox: Box{24, 24, 24, 24}, Target: Box{0, 0, 24, 24}},

		// projections requiring translation and proportional scaling
		{ViewBox: Box{0, 0, 24, 24}, Target: Box{0, 0, 36, 36}},
		{ViewBox: Box{0, -24, 24, 24}, Target: Box{0, 0, 36, 36}},
		{ViewBox: Box{-24, 0, 24, 24}, Target: Box{0, 0, 36, 36}},
		{ViewBox: Box{-24, -24, 24, 24}, Target: Box{0, 0, 36, 36}},

		// projections requiring arbitrary transformations
		{ViewBox: Box{8, 0, 24, 26}, Target: Box{-16, 16, 36, 26}},
		{ViewBox: Box{0, 8, 24, 26}, Target: Box{-8, -8, 64, 8}},
		{ViewBox: Box{-16, -16, 24, 26}, Target: Box{-4, 8, 12, 12}},
		{ViewBox: Box{-4.5, 2.0, 24.5, 26.125}, Target: Box{-4, 8, 16.125, 12.5}},
	}

	for i, test := range tests {
		var icon SvgIcon
		icon.ViewBox = test.ViewBox
		icon.SetTarget(test.Target.X, test.Target.Y, test.Target.W, test.Target.H)

		var expectedX, expectedY [4]float64
		expectedX[0], expectedY[0] = test.Target.X, test.Target.Y
		expectedX[1], expectedY[1] = test.Target.X+test.Target.W, test.Target.Y
		expectedX[2], expectedY[2] = test.Target.X+test.Target.W, test.Target.Y+test.Target.H
		expectedX[3], expectedY[3] = test.Target.X, test.Target.Y+test.Target.H

		// Apply the Transform matrix computed in SetTarget to each ViewBox
		// corner. The result of this projection must match Target
		var actualX, actualY [4]float64
		actualX[0], actualY[0] = icon.Transform.Transform(test.ViewBox.X, test.ViewBox.Y)
		actualX[1], actualY[1] = icon.Transform.Transform(test.ViewBox.X+test.ViewBox.W, test.ViewBox.Y)
		actualX[2], actualY[2] = icon.Transform.Transform(test.ViewBox.X+test.ViewBox.W, test.ViewBox.Y+test.ViewBox.H)
		actualX[3], actualY[3] = icon.Transform.Transform(test.ViewBox.X, test.ViewBox.Y+test.ViewBox.H)

		for n := 0; n < 4; n++ {
			if actualX[n] != expectedX[n] || actualY[n] != expectedY[n] {
				t.Fatalf(
					"test#%d: point %d: expected (%f, %f), got (%f, %f) %v",
					i, n, expectedX[n], expectedY[n], actualX[n], actualY[n], test,
				)
			}
		}
	}
}
